import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { TransformControls } from 'three/examples/jsm/controls/TransformControls.js';
import { exampleGameAdapter } from './games/example-game/adapter';
import { applyEditorTheme, type FrameworkProject, type LevelEntity } from './framework';
import './example-game.css';

const root = document.querySelector<HTMLDivElement>('#example-app')!;
applyEditorTheme(exampleGameAdapter.config.theme);
document.title = exampleGameAdapter.config.branding.applicationName;
root.innerHTML = `<header><h1>ExampleGame Level Editor</h1><input id="project-name" value="Example Level"><button id="new">New</button><button id="save">Save</button><button id="load">Load</button><button id="export">Export</button><input id="file" type="file" accept=".json" hidden></header><main><aside><h2>Palette</h2><div id="palette"></div><h2>Transform</h2><button data-mode="translate">Move</button><button data-mode="rotate">Rotate</button><button data-mode="scale">Resize</button><label>Snap <input id="snap" type="checkbox" checked></label></aside><section id="example-viewport"></section><aside><h2>Selection</h2><pre id="inspector">Nothing selected</pre><label>Solid <input id="solid" type="checkbox" disabled></label><button id="delete">Delete</button><p>Orbit: right mouse. Select: click. Transform using the centred gizmo.</p></aside></main>`;
let project = exampleGameAdapter.createProject('Example Level');
root.querySelector('h1')!.textContent = exampleGameAdapter.config.branding.editorTitle;
const viewport = document.querySelector<HTMLElement>('#example-viewport')!;
const scene = new THREE.Scene(); scene.background = new THREE.Color(exampleGameAdapter.config.preview.background); scene.add(new THREE.GridHelper(exampleGameAdapter.config.grid.size * exampleGameAdapter.config.grid.subdivisions, exampleGameAdapter.config.grid.subdivisions, exampleGameAdapter.config.theme.colours.grid, exampleGameAdapter.config.theme.colours.grid));
const camera = new THREE.PerspectiveCamera(60, 1, .1, 500); camera.position.set(exampleGameAdapter.config.preview.cameraPosition.x, exampleGameAdapter.config.preview.cameraPosition.y, exampleGameAdapter.config.preview.cameraPosition.z); camera.lookAt(0, 0, 0);
const renderer = new THREE.WebGLRenderer({ antialias: true }); viewport.append(renderer.domElement);
const orbit = new OrbitControls(camera, renderer.domElement); const transform = new TransformControls(camera, renderer.domElement); scene.add(transform.getHelper());
scene.add(new THREE.HemisphereLight(0xffffff, 0x334155, 2)); const meshes = new Map<string, THREE.Mesh>(); let selected: THREE.Mesh | null = null;
const material = new THREE.MeshStandardMaterial({ color: 0x38bdf8 });
function geometry(shape: string) { if (shape === 'cylinder') return new THREE.CylinderGeometry(.5, .5, 1, 24); if (shape === 'ramp') { const wedge = new THREE.BufferGeometry(); wedge.setAttribute('position', new THREE.Float32BufferAttribute([-.5,-.5,-.5,.5,-.5,-.5,-.5,.5,-.5,.5,.5,-.5,-.5,-.5,.5,.5,-.5,.5], 3)); wedge.setIndex([0,2,1,1,2,3,0,1,4,1,5,4,0,4,2,2,4,3,3,4,5,2,3,4,1,3,5]); wedge.computeVertexNormals(); return wedge; } return new THREE.BoxGeometry(1, 1, 1); }
function syncEntity(mesh: THREE.Mesh) { const entity = project.entities.find(({ id }) => id === mesh.userData.entityId)!; entity.transform = { position: { x: mesh.position.x, y: mesh.position.y, z: mesh.position.z }, rotation: { x: mesh.rotation.x, y: mesh.rotation.y, z: mesh.rotation.z }, scale: { x: mesh.scale.x, y: mesh.scale.y, z: mesh.scale.z } }; document.querySelector('#inspector')!.textContent = JSON.stringify(entity.transform, null, 2); }
function add(assetId: string, existing?: LevelEntity) { const definition = exampleGameAdapter.assets.find(({ id }) => id === assetId)!; const entity = existing || { id: crypto.randomUUID(), assetId, transform: structuredClone(definition.defaultTransform), properties: { solid: true } }; if (!existing) project.entities.push(entity); const mesh = new THREE.Mesh(geometry(definition.shape), material.clone()); mesh.userData.entityId = entity.id; mesh.position.set(entity.transform.position.x, entity.transform.position.y, entity.transform.position.z); mesh.rotation.set(entity.transform.rotation.x, entity.transform.rotation.y, entity.transform.rotation.z); mesh.scale.set(entity.transform.scale.x, entity.transform.scale.y, entity.transform.scale.z); scene.add(mesh); meshes.set(entity.id, mesh); select(mesh); }
const solid = document.querySelector<HTMLInputElement>('#solid')!;
function select(mesh: THREE.Mesh | null) { selected = mesh; solid.disabled = !mesh; if (mesh) { transform.attach(mesh); syncEntity(mesh); const entity = project.entities.find(({ id }) => id === mesh.userData.entityId)!; solid.checked = entity.properties.solid !== false; } else { transform.detach(); document.querySelector('#inspector')!.textContent = 'Nothing selected'; solid.checked = false; } }
solid.onchange = () => { if (!selected) return; const entity = project.entities.find(({ id }) => id === selected!.userData.entityId)!; entity.properties.solid = solid.checked; };
exampleGameAdapter.assets.forEach(({ id, label }) => { const button = document.createElement('button'); button.textContent = label; button.onclick = () => add(id); document.querySelector('#palette')!.append(button); });
transform.addEventListener('objectChange', () => { if (selected) syncEntity(selected); }); transform.setTranslationSnap(exampleGameAdapter.config.snapping.translation); transform.setScaleSnap(exampleGameAdapter.config.snapping.scale); transform.setRotationSnap(THREE.MathUtils.degToRad(exampleGameAdapter.config.snapping.rotationDegrees));
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach((button) => button.onclick = () => transform.setMode(button.dataset.mode as 'translate' | 'rotate' | 'scale'));
document.querySelector<HTMLInputElement>('#snap')!.checked = exampleGameAdapter.config.snapping.enabled; document.querySelector<HTMLInputElement>('#snap')!.onchange = (event) => { const enabled = (event.target as HTMLInputElement).checked; transform.setTranslationSnap(enabled ? exampleGameAdapter.config.snapping.translation : null); transform.setScaleSnap(enabled ? exampleGameAdapter.config.snapping.scale : null); };
renderer.domElement.onclick = (event) => { const rect = renderer.domElement.getBoundingClientRect(); const pointer = new THREE.Vector2((event.clientX - rect.left) / rect.width * 2 - 1, -(event.clientY - rect.top) / rect.height * 2 + 1); const ray = new THREE.Raycaster(); ray.setFromCamera(pointer, camera); select(ray.intersectObjects([...meshes.values()])[0]?.object as THREE.Mesh || null); };
document.querySelector<HTMLButtonElement>('#delete')!.onclick = () => { if (!selected) return; const id = selected.userData.entityId; scene.remove(selected); meshes.delete(id); project.entities = project.entities.filter((entity) => entity.id !== id); select(null); };
function download(name: string, text: string) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: 'application/json' })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
document.querySelector<HTMLInputElement>('#project-name')!.oninput = (event) => { project.name = (event.target as HTMLInputElement).value; }; document.querySelector<HTMLButtonElement>('#save')!.onclick = () => download('example-level.json', exampleGameAdapter.serialize(project)); document.querySelector<HTMLButtonElement>('#export')!.onclick = async () => download('example-runtime.json', `${JSON.stringify(await exampleGameAdapter.exportRuntime(project), null, 2)}\n`);
document.querySelector<HTMLButtonElement>('#new')!.onclick = () => { meshes.forEach((mesh) => scene.remove(mesh)); meshes.clear(); project = exampleGameAdapter.createProject('Example Level'); select(null); };
const file = document.querySelector<HTMLInputElement>('#file')!; document.querySelector<HTMLButtonElement>('#load')!.onclick = () => file.click(); file.onchange = async () => { const next = exampleGameAdapter.deserialize(await file.files![0].text()); meshes.forEach((mesh) => scene.remove(mesh)); meshes.clear(); project = next; document.querySelector<HTMLInputElement>('#project-name')!.value = project.name; project.entities.forEach((entity) => add(entity.assetId, entity)); };
function frame() { const width = viewport.clientWidth; const height = viewport.clientHeight; renderer.setSize(width, height, false); camera.aspect = width / Math.max(height, 1); camera.updateProjectionMatrix(); orbit.update(); renderer.render(scene, camera); requestAnimationFrame(frame); } frame();
